class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'm'
        self.UnzipMirrorCommand = 'um'
        self.TarMirrorCommand = 'tm'
        self.CancelMirror = 'cm'
        self.CancelAllCommand = 'ca'
        self.ListCommand = 'l'
        self.StatusCommand = 'ms'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'h'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'c'
        self.CountCommand = 'cnt'
        self.WatchCommand = 'w'
        self.TarWatchCommand = 'tw'
        self.DeleteCommand = 'd'
        self.UsageCommand = 'usage'

BotCommands = _BotCommands()
